service: kmd-blocknotify

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128
  region: ap-southeast-2
  stage: v0
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: blocknotify/create.create
    events:
      - http:
          path: blocknotify
          method: post
          cors: true

  list:
    handler: blocknotify/list.list
    events:
      - http:
          path: blocknotify
          method: get
          cors: true

  get:
    handler: blocknotify/get.get
    events:
      - http:
          path: blocknotify/{id}
          method: get
          cors: true

  update:
    handler: blocknotify/update.update
    events:
      - http:
          path: blocknotify/{id}
          method: put
          cors: true

  delete:
    handler: blocknotify/delete.delete
    events:
      - http:
          path: blocknotify/{id}
          method: delete
          cors: true

resources:
  Resources:
    TaskDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

plugins:
  - serverless-finch
  - serverless-aws-documentation

custom:
  client:
    bucketName: imylomylo-scaletest-2018
    distributionFolder: client/dist

  documentation:
    version: '0'
    summary: 'Block Notify API'
    description: 'A block notfiy API for blockchain utility'
    resources:
      -
        path: "blocknotify"
        description: "Path used for blocknotify scripts"
      -
        path: "blocknotify/{id}"
        description: "Path used for getting, updating and deleting a blocknotify"
    models:
      -
        name: "blocknotify"
        description: "a blocknotify object"
        contentType: "application/json"
        schema:
          type: object
          properties:
            id:
              type: string
              format: uuid
            height:
              type: string
              format: string
            blockhash:
              type: string
              format: string
            txcount:
              type: string
              format: string
            size:
              type: string
              format: string
            createdAt:
              type: number
            updatedAt:
              type: number
          required:
            - id
            - height
            - blockhash
            - txcount
            - size
            - createdAt
            - updatedAt
      -
        name: "blocknotifyCreateRequest"
        description: "a blocknotify create request model"
        contentType: "application/json"
        schema:
          ${self:custom.documentation.models}
      -
        name: "awsError"
        description: "an aws internal server error, usually with status code 502 (bad gateway)"
        contentType: "application/json"
        schema:
          type: object
          properties:
            message:
              type: string
          required:
            - message
